/* User Agent */
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('friendly-scanner', 'SIPVicious (http://blog.sipvicious.org)', 'ua', 'yes', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('sundayddr', 'SIP scanner', 'ua', 'yes', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('sip-scan', 'SIP scanner', 'ua', 'yes', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('iWar', 'SIP scanner', 'ua', 'yes', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('sipsak', 'SIP stress testing tool', 'ua', 'yes', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('sipcli', 'SipCli - KaplanSoft (https://www.kaplansoft.com/sipcli/)', 'ua', 'yes', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('VaxSIPUserAgent', 'VaxVoIP SIP SDK (http://www.vaxvoip.com)', 'ua', 'yes', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('SimpleSIP', 'SIP scanner', 'ua', 'yes', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('SIP Call', 'SIP scanner', 'ua', 'yes', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('Ozeki', 'VoIP SIP SDK (http://www.voip-sip-sdk.com)', 'ua', 'yes', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('VoIPSec', 'SIP scanner', 'ua', 'yes', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('pplsip', 'Sippts - Pepelux (https://github.com/Pepelux/sippts)', 'ua', 'yes', 'response', '403', '8==========D');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('SIPScan', 'SIP scanner', 'ua', 'yes', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('Conaito', 'VoIP SIP SDK (http://conaito.com/products/voip-sip-client-sdk)', 'ua', 'yes', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('UsaAirport', 'SIP scanner', 'ua', 'yes', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('PortSIP VoIP SDK', 'PortSIP VoIP SDK (https://www.portsip.com)', 'ua', 'yes', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('VoIP SIP v11.0.0', 'Ozki VoIP SIP SDK', 'ua', 'yes', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('zxcvfdf11', 'SIP scanner', 'ua', 'no', 'drop', '', '');

/* User */
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('sipvicious', 'Fromname used by SIPVicious', 'user', 'yes', 'drop', '', '');

/* Domain */
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('1.1.1.1', 'Domain used by SIPVicious', 'domain', 'yes', 'drop', '', '');

/* Country */
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('AI', 'Anguilla', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('AL', 'Albania', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('AM', 'Armenia', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('AO', 'Angola', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('AU', 'Australia', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('AW', 'Aruba', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('BB', 'Barbados', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('BD', 'Bangladesh', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('BF', 'Burkina Faso', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('BG', 'Bulgaria', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('BI', 'Burundi', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('BS', 'Bahamas', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('BT', 'Bhutan', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('BW', 'Botswana', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('CN', 'China', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('CR', 'Costa Rica', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('CU', 'Cuba', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('DM', 'Dominica', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('EC', 'Ecuador', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('EE', 'Estonia', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('ER', 'Eritrea', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('GA', 'Gabon', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('GE', 'Georgia', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('GH', 'Ghana', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('GI', 'Gibraltar', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('GM', 'Gambia', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('GT', 'Guatemala', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('GU', 'Guam', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('GY', 'Guyana', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('HK', 'Hong Kong', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('HN', 'Honduras', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('HT', 'Haiti', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('ID', 'Indonesia', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('IL', 'Israel', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('IN', 'India', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('IQ', 'Iraq', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('JM', 'Jamaica', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('KI', 'Kiribati', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('KW', 'Kuwait', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('LI', 'Liechtenstein', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('LK', 'Sri Lanka', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('LR', 'Liberia', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('LS', 'Lesotho', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('MC', 'Monaco', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('ME', 'Montenegro', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('ML', 'Mali', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('MM', 'Myanmar', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('MN', 'Mongolia', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('MO', 'Macao', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('MR', 'Mauritania', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('MS', 'Montserrat', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('MT', 'Malta', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('MW', 'Malawi', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('MZ', 'Mozambique', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('NA', 'Namibia', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('NE', 'Niger', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('NG', 'Nigeria', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('NI', 'Nicaragua', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('NP', 'Nepal', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('NR', 'Nauru', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('NU', 'Niue', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('OM', 'Oman', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('PA', 'Panama', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('PE', 'Peru', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('PK', 'Pakistan', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('PR', 'Puerto Rico', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('PY', 'Paraguay', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('QA', 'Qatar', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('RS', 'Serbia', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('SD', 'Sudan', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('SM', 'San Marino', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('SN', 'Senegal', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('SO', 'Somalia', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('SV', 'El Salvador', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('TD', 'Chad', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('TG', 'Togo', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('TK', 'Tokelau', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('TM', 'Turkmenistan', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('TV', 'Tuvalu', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('UG', 'Uganda', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('UY', 'Uruguay', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('UZ', 'Uzbekistan', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('VU', 'Vanuatu', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('YE', 'Yemen', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('YT', 'Mayotte', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('ZM', 'Zambia', 'country', 'no', 'drop', '', '');
INSERT INTO `blacklist` (`value`, `detail`, `type`, `ban`, `action`, `code`, `text`) VALUES('ZW', 'Zimbabwe', 'country', 'no', 'drop', '', '');

