/* Destinations */
INSERT INTO `destinations_deny` (`country`) VALUES('Anguilla');
INSERT INTO `destinations_deny` (`country`) VALUES('Albania');
INSERT INTO `destinations_deny` (`country`) VALUES('Armenia');
INSERT INTO `destinations_deny` (`country`) VALUES('Angola');
INSERT INTO `destinations_deny` (`country`) VALUES('Australia');
INSERT INTO `destinations_deny` (`country`) VALUES('Aruba');
INSERT INTO `destinations_deny` (`country`) VALUES('Barbados');
INSERT INTO `destinations_deny` (`country`) VALUES('Bangladesh');
INSERT INTO `destinations_deny` (`country`) VALUES('Burkina Faso');
INSERT INTO `destinations_deny` (`country`) VALUES('Bulgaria');
INSERT INTO `destinations_deny` (`country`) VALUES('Burundi');
INSERT INTO `destinations_deny` (`country`) VALUES('Bahamas');
INSERT INTO `destinations_deny` (`country`) VALUES('Bhutan');
INSERT INTO `destinations_deny` (`country`) VALUES('Botswana');
INSERT INTO `destinations_deny` (`country`) VALUES('China');
INSERT INTO `destinations_deny` (`country`) VALUES('Costa Rica');
INSERT INTO `destinations_deny` (`country`) VALUES('Cuba');
INSERT INTO `destinations_deny` (`country`) VALUES('Dominica');
INSERT INTO `destinations_deny` (`country`) VALUES('Ecuador');
INSERT INTO `destinations_deny` (`country`) VALUES('Estonia');
INSERT INTO `destinations_deny` (`country`) VALUES('Eritrea');
INSERT INTO `destinations_deny` (`country`) VALUES('Gabon');
INSERT INTO `destinations_deny` (`country`) VALUES('Georgia');
INSERT INTO `destinations_deny` (`country`) VALUES('Ghana');
INSERT INTO `destinations_deny` (`country`) VALUES('Gibraltar');
INSERT INTO `destinations_deny` (`country`) VALUES('Gambia');
INSERT INTO `destinations_deny` (`country`) VALUES('Guatemala');
INSERT INTO `destinations_deny` (`country`) VALUES('Guam');
INSERT INTO `destinations_deny` (`country`) VALUES('Guyana');
INSERT INTO `destinations_deny` (`country`) VALUES('Hong Kong');
INSERT INTO `destinations_deny` (`country`) VALUES('Honduras');
INSERT INTO `destinations_deny` (`country`) VALUES('Haiti');
INSERT INTO `destinations_deny` (`country`) VALUES('Indonesia');
INSERT INTO `destinations_deny` (`country`) VALUES('Israel');
INSERT INTO `destinations_deny` (`country`) VALUES('India');
INSERT INTO `destinations_deny` (`country`) VALUES('Iraq');
INSERT INTO `destinations_deny` (`country`) VALUES('Jamaica');
INSERT INTO `destinations_deny` (`country`) VALUES('Kiribati');
INSERT INTO `destinations_deny` (`country`) VALUES('Kuwait');
INSERT INTO `destinations_deny` (`country`) VALUES('Liechtenstein');
INSERT INTO `destinations_deny` (`country`) VALUES('Sri Lanka');
INSERT INTO `destinations_deny` (`country`) VALUES('Liberia');
INSERT INTO `destinations_deny` (`country`) VALUES('Lesotho');
INSERT INTO `destinations_deny` (`country`) VALUES('Monaco');
INSERT INTO `destinations_deny` (`country`) VALUES('Montenegro');
INSERT INTO `destinations_deny` (`country`) VALUES('Mali');
INSERT INTO `destinations_deny` (`country`) VALUES('Myanmar');
INSERT INTO `destinations_deny` (`country`) VALUES('Mongolia');
INSERT INTO `destinations_deny` (`country`) VALUES('Macao');
INSERT INTO `destinations_deny` (`country`) VALUES('Mauritania');
INSERT INTO `destinations_deny` (`country`) VALUES('Montserrat');
INSERT INTO `destinations_deny` (`country`) VALUES('Malta');
INSERT INTO `destinations_deny` (`country`) VALUES('Malawi');
INSERT INTO `destinations_deny` (`country`) VALUES('Mozambique');
INSERT INTO `destinations_deny` (`country`) VALUES('Namibia');
INSERT INTO `destinations_deny` (`country`) VALUES('Niger');
INSERT INTO `destinations_deny` (`country`) VALUES('Nigeria');
INSERT INTO `destinations_deny` (`country`) VALUES('Nicaragua');
INSERT INTO `destinations_deny` (`country`) VALUES('Nepal');
INSERT INTO `destinations_deny` (`country`) VALUES('Nauru');
INSERT INTO `destinations_deny` (`country`) VALUES('Niue');
INSERT INTO `destinations_deny` (`country`) VALUES('Oman');
INSERT INTO `destinations_deny` (`country`) VALUES('Panama');
INSERT INTO `destinations_deny` (`country`) VALUES('Peru');
INSERT INTO `destinations_deny` (`country`) VALUES('Pakistan');
INSERT INTO `destinations_deny` (`country`) VALUES('Puerto Rico');
INSERT INTO `destinations_deny` (`country`) VALUES('Paraguay');
INSERT INTO `destinations_deny` (`country`) VALUES('Qatar');
INSERT INTO `destinations_deny` (`country`) VALUES('Serbia');
INSERT INTO `destinations_deny` (`country`) VALUES('Sudan');
INSERT INTO `destinations_deny` (`country`) VALUES('San Marino');
INSERT INTO `destinations_deny` (`country`) VALUES('Senegal');
INSERT INTO `destinations_deny` (`country`) VALUES('Somalia');
INSERT INTO `destinations_deny` (`country`) VALUES('El Salvador');
INSERT INTO `destinations_deny` (`country`) VALUES('Chad');
INSERT INTO `destinations_deny` (`country`) VALUES('Togo');
INSERT INTO `destinations_deny` (`country`) VALUES('Tokelau');
INSERT INTO `destinations_deny` (`country`) VALUES('Turkmenistan');
INSERT INTO `destinations_deny` (`country`) VALUES('Tuvalu');
INSERT INTO `destinations_deny` (`country`) VALUES('Uganda');
INSERT INTO `destinations_deny` (`country`) VALUES('Uruguay');
INSERT INTO `destinations_deny` (`country`) VALUES('Uzbekistan');
INSERT INTO `destinations_deny` (`country`) VALUES('Vanuatu');
INSERT INTO `destinations_deny` (`country`) VALUES('Yemen');
INSERT INTO `destinations_deny` (`country`) VALUES('Mayotte');
INSERT INTO `destinations_deny` (`country`) VALUES('Zambia');
INSERT INTO `destinations_deny` (`country`) VALUES('Zimbabwe');

